// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FolderSynchronizer.E2ETests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Folder synchronization")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class FolderSynchronizationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Folder synchronization", @"Acceptance Criterias:

AC-1: Synchronization must be one-way: after the synchronization content of the replica
folder should be modified to exactly match content of the source folder;

AC-2: Synchronization should be performed periodically;
AC-3: File creation/copying/removal operations should be logged to a file and to the
console output;
AC-4: Folder paths, synchronization interval and log file path should be provided using
the command line arguments;", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "FolderSynchronization.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/FolderSynchronization.feature.ndjson", 7);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Initial synchronization copies source contents to replica")]
        [global::NUnit.Framework.CategoryAttribute("AC-1")]
        [global::NUnit.Framework.CategoryAttribute("AC-3")]
        [global::NUnit.Framework.CategoryAttribute("AC-4")]
        public async global::System.Threading.Tasks.Task InitialSynchronizationCopiesSourceContentsToReplica()
        {
            string[] tagsOfScenario = new string[] {
                    "AC-1",
                    "AC-3",
                    "AC-4"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Initial synchronization copies source contents to replica", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
    await testRunner.GivenAsync("a source folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table1.AddRow(new string[] {
                            "E2E-TC-1.txt"});
                table1.AddRow(new string[] {
                            "E2E-TC-1.csv"});
                table1.AddRow(new string[] {
                            "E2E-TC-1.png"});
#line 19
    await testRunner.AndAsync("the source folder contains the following files:", ((string)(null)), table1, "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "folder"});
                table2.AddRow(new string[] {
                            "empty-folder"});
                table2.AddRow(new string[] {
                            "nested-1/nested-2"});
#line 24
    await testRunner.AndAsync("the source folder contains the following folders:", ((string)(null)), table2, "And ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table3.AddRow(new string[] {
                            "E2E-TC-1.txt"});
                table3.AddRow(new string[] {
                            "E2E-TC-1.csv"});
#line 28
    await testRunner.AndAsync("the folder \"nested-1/nested-2\" in the source contains the following files:", ((string)(null)), table3, "And ");
#line hidden
#line 32
    await testRunner.AndAsync("an empty replica folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.WhenAsync("I run the folder synchronizer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "folder"});
                table4.AddRow(new string[] {
                            "empty-folder"});
                table4.AddRow(new string[] {
                            "nested-1/nested-2"});
#line 34
    await testRunner.ThenAsync("the replica folder contains the following folders:", ((string)(null)), table4, "Then ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table5.AddRow(new string[] {
                            "E2E-TC-1.txt"});
                table5.AddRow(new string[] {
                            "E2E-TC-1.csv"});
                table5.AddRow(new string[] {
                            "E2E-TC-1.png"});
#line 38
    await testRunner.AndAsync("the replica folder contains the following files:", ((string)(null)), table5, "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table6.AddRow(new string[] {
                            "E2E-TC-1.txt"});
                table6.AddRow(new string[] {
                            "E2E-TC-1.csv"});
#line 43
    await testRunner.AndAsync("the folder \"nested-1/nested-2\" in the replica contains the following files:", ((string)(null)), table6, "And ");
#line hidden
#line 47
 await testRunner.AndAsync("the log file is generated and is not empty", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Synchronization should be performed periodically")]
        [global::NUnit.Framework.CategoryAttribute("AC-1")]
        [global::NUnit.Framework.CategoryAttribute("AC-2")]
        [global::NUnit.Framework.CategoryAttribute("AC-3")]
        [global::NUnit.Framework.CategoryAttribute("AC-4")]
        public async global::System.Threading.Tasks.Task SynchronizationShouldBePerformedPeriodically()
        {
            string[] tagsOfScenario = new string[] {
                    "AC-1",
                    "AC-2",
                    "AC-3",
                    "AC-4"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Synchronization should be performed periodically", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
     await testRunner.GivenAsync("a source folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table7.AddRow(new string[] {
                            "E2E-TC-1.txt"});
#line 55
     await testRunner.AndAsync("the source folder contains the following files:", ((string)(null)), table7, "And ");
#line hidden
#line 58
     await testRunner.AndAsync("an empty replica folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
     await testRunner.WhenAsync("I run the folder synchronizer with sync interval 3 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table8.AddRow(new string[] {
                            "E2E-TC-1.txt"});
#line 60
     await testRunner.ThenAsync("the replica folder contains the following files:", ((string)(null)), table8, "Then ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "original",
                            "new"});
                table9.AddRow(new string[] {
                            "E2E-TC-1.txt",
                            "E2E-TC-1-UPDATED.txt"});
#line 63
     await testRunner.WhenAsync("I rename the following files in the source folder:", ((string)(null)), table9, "When ");
#line hidden
#line 66
     await testRunner.AndAsync("I wait 3 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table10.AddRow(new string[] {
                            "E2E-TC-1-UPDATED.txt"});
#line 67
     await testRunner.ThenAsync("the replica folder contains the following files:", ((string)(null)), table10, "Then ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table11.AddRow(new string[] {
                            "E2E-TC-1.txt"});
#line 70
     await testRunner.AndAsync("the replica folder does not contain the following files:", ((string)(null)), table11, "And ");
#line hidden
#line 73
    await testRunner.AndAsync("the log file is generated and is not empty", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Obsolete files and folders are removed from replica")]
        [global::NUnit.Framework.CategoryAttribute("AC-1")]
        [global::NUnit.Framework.CategoryAttribute("AC-3")]
        [global::NUnit.Framework.CategoryAttribute("AC-4")]
        public async global::System.Threading.Tasks.Task ObsoleteFilesAndFoldersAreRemovedFromReplica()
        {
            string[] tagsOfScenario = new string[] {
                    "AC-1",
                    "AC-3",
                    "AC-4"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Obsolete files and folders are removed from replica", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 78
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 79
    await testRunner.GivenAsync("a source folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table12.AddRow(new string[] {
                            "E2E-TC-1.txt"});
#line 80
    await testRunner.AndAsync("the source folder contains the following files:", ((string)(null)), table12, "And ");
#line hidden
#line 83
    await testRunner.AndAsync("an empty replica folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table13.AddRow(new string[] {
                            "obsolete-file.txt"});
#line 84
    await testRunner.AndAsync("the replica folder contains the following files:", ((string)(null)), table13, "And ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "folder"});
                table14.AddRow(new string[] {
                            "obsolete-folder"});
                table14.AddRow(new string[] {
                            "obsolete-folder/nested"});
#line 87
    await testRunner.AndAsync("the replica folder contains the following folders:", ((string)(null)), table14, "And ");
#line hidden
#line 91
    await testRunner.WhenAsync("I run the folder synchronizer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table15.AddRow(new string[] {
                            "E2E-TC-1.txt"});
#line 92
    await testRunner.ThenAsync("the replica folder contains the following files:", ((string)(null)), table15, "Then ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table16.AddRow(new string[] {
                            "obsolete-file.txt"});
#line 95
    await testRunner.AndAsync("the replica folder does not contain the following files:", ((string)(null)), table16, "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "folder"});
                table17.AddRow(new string[] {
                            "obsolete-folder"});
#line 98
    await testRunner.AndAsync("the replica folder does not contain the following folders:", ((string)(null)), table17, "And ");
#line hidden
#line 101
    await testRunner.AndAsync("the log file is generated and is not empty", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Changed file content is synchronized to replica")]
        [global::NUnit.Framework.CategoryAttribute("AC-1")]
        [global::NUnit.Framework.CategoryAttribute("AC-3")]
        [global::NUnit.Framework.CategoryAttribute("AC-4")]
        public async global::System.Threading.Tasks.Task ChangedFileContentIsSynchronizedToReplica()
        {
            string[] tagsOfScenario = new string[] {
                    "AC-1",
                    "AC-3",
                    "AC-4"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Changed file content is synchronized to replica", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 106
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 107
  await testRunner.GivenAsync("a source folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table18.AddRow(new string[] {
                            "E2E-TC-1.txt"});
#line 108
  await testRunner.AndAsync("the source folder contains the following files:", ((string)(null)), table18, "And ");
#line hidden
#line 111
  await testRunner.AndAsync("an empty replica folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
  await testRunner.WhenAsync("I run the folder synchronizer with sync interval 1 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table19.AddRow(new string[] {
                            "E2E-TC-1.txt"});
#line 113
  await testRunner.ThenAsync("the replica folder contains the following files:", ((string)(null)), table19, "Then ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "file",
                            "New file content"});
                table20.AddRow(new string[] {
                            "E2E-TC-1.txt",
                            "This is updated test file content 123!@#"});
#line 116
  await testRunner.WhenAsync("I change the content of the following file in the source folder:", ((string)(null)), table20, "When ");
#line hidden
#line 119
  await testRunner.ThenAsync("the content of the file \"E2E-TC-1.txt\" in the replica should be:", "This is updated test file content 123!@#", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Synchronization events are logged to the console")]
        public async global::System.Threading.Tasks.Task SynchronizationEventsAreLoggedToTheConsole()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Synchronization events are logged to the console", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 124
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 125
  await testRunner.GivenAsync("a source folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table21.AddRow(new string[] {
                            "E2E-TC-1.txt"});
#line 126
  await testRunner.AndAsync("the source folder contains the following files:", ((string)(null)), table21, "And ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "folder"});
                table22.AddRow(new string[] {
                            "empty-folder"});
#line 129
  await testRunner.AndAsync("the source folder contains the following folders:", ((string)(null)), table22, "And ");
#line hidden
#line 132
  await testRunner.AndAsync("an empty replica folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "folder"});
                table23.AddRow(new string[] {
                            "obsolete-folder"});
#line 133
  await testRunner.AndAsync("the replica folder contains the following folders:", ((string)(null)), table23, "And ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "file"});
                table24.AddRow(new string[] {
                            "obsolete-file.txt"});
#line 136
  await testRunner.AndAsync("the replica folder contains the following files:", ((string)(null)), table24, "And ");
#line hidden
#line 139
  await testRunner.WhenAsync("I run the folder synchronizer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "Message",
                            "Item"});
                table25.AddRow(new string[] {
                            "Copied file from source",
                            "E2E-TC-1.txt"});
                table25.AddRow(new string[] {
                            "Created directory in replica",
                            "empty-folder"});
                table25.AddRow(new string[] {
                            "Removed obsolete directory",
                            "obsolete-folder"});
                table25.AddRow(new string[] {
                            "Removed obsolete file",
                            "obsolete-file.txt"});
#line 141
  await testRunner.ThenAsync("the console output contains the following messages:", ((string)(null)), table25, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
